### ISSUE TITLE
Doc issues

### ISSUE THREAD

**Issue by cheater** [mgattozzi/curryrs#3]
Hi! Really nice lib. I've read the readme and there were some things I would change.

- the sentence "In the case of the latter this only occurs for the Boolean type" doesn't make sense to me. Could you say this differently?

- the function 'triple_input' doesn't triple the input. consider calling it cube_input, or changing the body to 3*x.

- you first use a function called double_input in Rust to create a function called doubleInput in Haskell through FFI. Then you use an unrelated function called doubleInput and import it into Rust. That's confusing. Use a function with a different name in the second example, for example quintupleInput = 5*x.

- rather than call functions double_input, square_input etc call them double, square. Obviously functions work on their inputs. :)

Thanks!

**Comment by mgattozzi** [comment]
Thanks for bringing these to my attention! I wasn't as thorough as I should have been with the README file. When I get the chance I'll be sure to update it.

**Comment by mgattozzi** [comment]
I went ahead and implemented your suggestions [here](https://github.com/mgattozzi/curryrs/commit/739a4ff1d6c9ca9b8583c33dc7ea9aea38f6cbdd). Thanks for opening up the issue!
